name: GREG
favicon: null
layout_spectrum: 0.6645626367535442
typography_spectrum: 0.017812272300943732
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5968677806667984
  lightness: 0.6999495148193091
  saturation: 0.5953822208102793
  rhythmicContrast: 0.4260547896847129
purpose: []
